/*
 * Project Euler Problem 2:
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
#include <iostream>
using std::cout;

#include "tinyprof.h"
uint64_t start, total, l1s, l1t;

int main() {
start = rdtsc();
  uint64_t a = 1;
  uint64_t b = 1;
  uint64_t c = a + b;
  uint64_t sum = 0;
  const uint64_t MAX = 4000000;
l1s = rdtsc();
  while (c <= MAX) {
    if (0 == (c & 1)) {
      sum += c;
    }
    a = b;
    b = c;
    c = a + b;
  }
l1t = rdtsc() - l1s;
  cout << sum << '\n';
total = rdtsc() - start;

  cerr << total << ',' << l1t << '\n';
}
