../libquantum: classic.c  complex.c  decoherence.c  expn.c  gates.c  matrix.c  measure.c  oaddn.c  objcode.c  omuln.c  qec.c  qft.c  qureg.c  shor.c  specrand.c  version.c
	clang -DSPEC_CPU -DSPEC_CPU_LINUX classic.c  complex.c  decoherence.c  expn.c  gates.c  matrix.c  measure.c  oaddn.c  objcode.c  omuln.c  qec.c  qft.c  qureg.c  shor.c  specrand.c  version.c -lm -o ../libquantum

../libquantum-prof: classic-prof.c  complex-prof.c  decoherence-prof.c  expn-prof.c  gates-prof.c  matrix-prof.c  measure-prof.c  oaddn-prof.c  objcode-prof.c  omuln-prof.c  qec-prof.c  qft-prof.c  qureg-prof.c  shor-prof.c  specrand-prof.c  version-prof.c
	clang -DSPEC_CPU -DSPEC_CPU_LINUX classic-prof.c  complex-prof.c  decoherence-prof.c  expn-prof.c  gates-prof.c  matrix-prof.c  measure-prof.c  oaddn-prof.c  objcode-prof.c  omuln-prof.c  qec-prof.c  qft-prof.c  qureg-prof.c  shor-prof.c  specrand-prof.c  version-prof.c -lm -o ../libquantum-prof
