../lbm: main.c main.h lbm.c lbm.h lbm_1d_array.h config.h
	clang main.c lbm.c -lm -o ../lbm

../lbm-prof: main-prof.c main.h lbm-prof.c lbm.h lbm_1d_array.h config.h
	clang main-prof.c lbm-prof.c -lm -o ../lbm-prof
